### ISSUE TITLE
Study plusのアプリを起動していない状態でのAuth

### ISSUE THREAD

**Issue by usatie** [studyplus/Studyplus-iOS-SDK#5]
StudyPlusのアプリを起動していない状態でAuthを行おうとすると、Studyplusのアプリが起動されるものの、Authの画面に行きません。（トップの通常の画面が表示されるだけです）
バックグラウンドで起動している状態でAuthを行えばちゃんと行われます。

**Comment by shibuym** [comment]
ご指摘頂きありがとうございます。
Studyplusアプリの不具合ですので改善いたします。
