### ISSUE TITLE
`-(BOOL)auth` と `-(BOOL)login` の使い分け方

### ISSUE THREAD

**Issue by yshrkt** [studyplus/Studyplus-iOS-SDK#6]
通常、`-(BOOL)auth`を使えばStudyplusとの連携ができると思いますが、
`-(BOOL)login`を呼ぶ必要があるケースはどんな場合がありますか？
状態を示すプロパティが`isConnected`しかなく、
コールバックを受け取るdelegateメソッドも同じで、
インターフェイスからは使い分け方がよくわからないので教えていただけたらと思います。

**Comment by shibuym** [comment]
authとloginは動作としては同じですが、Studyplusアプリに表示されるメッセージが異なります。

- auth
 - XXXXがあなたのStudyplusアカウントを利用することを許可しますか？
- login
 - あなたのStudyplusアカウントでXXXXにログインしますか？

Studyplusに勉強記録を投稿する用途でしたら、authをお使い頂ければと思います。
どうぞよろしくお願いいたします。

**Comment by yshrkt** [comment]
素早いご回答ありがとうございます。
上記、了解しました。
勉強記録を投稿する用途ですので、authを使うようにします。
