### ISSUE TITLE
IPv6対応が必要そう

### ISSUE THREAD

**Issue by yshrkt** [studyplus/Studyplus-iOS-SDK#7]
2016年6月からアプリ申請時にIPv6対応が必須になりますが、
Studyplus SDKが利用しているAFNetworkingのバージョンが古いため、
`AF_INET`や`sockaddr_in`が使われているようです。

https://developer.apple.com/news/?id=05042016a

https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW27

**Comment by shibuym** [comment]
ご連絡頂きありがとうございます。
対応が遅れており申し訳ありません。現在対応を進めておりますのでお待ちいただけますようお願いします。

**Comment by masashi-sutou** [comment]
@yshrkt 様

AFNetworkingのバージョンを最新の3.1.0にまで更新しました。
これでiPv6にも対応できたかと思います。

この度は、ご連絡頂きありがとうございました。
引き続き、studyplusをよろしくお願いします。

**Comment by yshrkt** [comment]
迅速なご対応ありがとうございます。
新バージョンを使わせていただきます。
